name: Sync Repositories

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  push:
    branches:
      - main  # Change this to your desired branch
defaults:
 run:
  working-directory: /home/runner/work
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ishavora31/CrawlerService  # Replace with the source repository owner and name
          path: CrawlerService

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          repository: ishavora31/CrawlerService-dummy  # Replace with the target repository owner and name
          path: CrawlerService-dummy

      - name: copy repositories content
        run: |
          cd /home/runner/work/CrawlerService/CrawlerService/
          cp -R CrawlerService/* CrawlerService-dummy/
          
      - name: push into target repo
        run: |
          cd /home/runner/work/CrawlerService/CrawlerService/CrawlerService-dummy/
          git remote add origin https://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@github.com/ishavora31/CrawlerService-dummy.git
          git config user.email "ivora2757@gmail.com"
          git config user.name "ishavora31"
          git add .
          git commit -m "Sync changes from source repository"
          git push
