name: Sync Repositories

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync repositories
        run: |
          git clone --bare https://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@github.com/ishavora31/CrawlerService.git
          cd CrawlerService.git
          git push --mirror https://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@github.com/ishavora31/CrawlerService-dummy.git
