name: Sync Repositories

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ishavora31/CrawlerService  # Replace with the source repository owner and name

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: ishavora31/CrawlerService-dummy  # Replace with the target repository owner and name

      - name: Sync repositories
        run: |
          cp -R ./CrawlerService/* ./CrawlerService-dummy/
          cd ./CrawlerService-dummy/
          git add .
          git commit -m "Sync changes from source repository"
          git push
